"""create complaints table

Revision ID: d70ab962bcd2
Revises: 
Create Date: 2026-09-25 18:22:25.283754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd70ab962bcd2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('reporter_contact', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('water', 'electricity', 'sanitation', 'roads', 'streetlights', 'other', name='category'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'normal', 'low', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'rejected', name='status'), nullable=False),
    sa.Column('ai_summary', sa.String(length=140), nullable=True),
    sa.Column('triaged_by', sa.String(length=50), nullable=False),
    sa.Column('triage_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(location) >= 3 AND char_length(location) <= 200', name='location_length'),
    sa.CheckConstraint('char_length(text) >= 10 AND char_length(text) <= 2000', name='text_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_created_at', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_status_priority', 'complaints', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_priority', table_name='complaints')
    op.drop_index('ix_created_at', table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###