apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicpulse

resources:
  - ../../base

images:
  - name: backend
    newName: civicpulse-backend
    newTag: dev
  - name: frontend
    newName: civicpulse-frontend
    newTag: dev

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3